apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-27020-set
  labels:
    app: mongodb-27020
spec:
  serviceName: "mongodb-27020-srvc"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-27020
  template:
    metadata:
      labels:
        app: mongodb-27020
    spec:
      containers:
      - name: mongodb-27020
        image: mongo:7.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-27020-data
          mountPath: /data/db
      volumes:
      - name: mongodb-27020-data
        hostPath:
          path: /mnt/factorymongodb
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-27020-srvc
  labels:
    app: mongodb-27020
spec:
  # type: LoadBalancer
  type: NodePort
  selector:
    app: mongodb-27020
  ports:
    - protocol: TCP
      name: mongodb-27020
      port: 27020
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 27017
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
#      nodePort: 32123
